#!/usr/bin/env python3
# encoding: utf-8
#
# This file is part of ckanext-doi
# Created by the Natural History Museum in London, UK

from ckan.plugins import interfaces


class IDoi(interfaces.Interface):
    """
    Hook into IDoi.
    """

    def should_manage_doi(self, pkg_dict):
        """
        Return whether ckanext-doi should create, mint, update, and expose a
        DOI table record for this package.

        Implementations can return False for packages whose identifiers are
        managed outside ckanext-doi/DataCite.

        :param pkg_dict: package dictionary
        :returns: True when ckanext-doi should manage the DOI, False otherwise
        """
        return True

    def build_metadata_dict(self, pkg_dict, metadata_dict, errors):
        """
        Extracts metadata from a pkg_dict for use in generating datacite DOIs. Extends
        the build_metadata_dict method from ckanext-doi.

        :param pkg_dict: package dictionary
        :param metadata_dict: the current metadata dict, created by the ckanext-doi extension and
                              any previous plugins implementing IDoi
        :param errors: a dictionary of metadata keys and errors generated by previous plugins;
                       this method should remove any keys that it successfully processes and
                       overwrites
        :returns: metadata_dict, errors
        """
        return metadata_dict, errors

    def build_xml_dict(self, metadata_dict, xml_dict):
        """
        Converts the metadata_dict into an xml_dict that can be passed to
        datacite_compat.tostring() and datacite_compat.validator.validate().
        Extends the build_xml_dict() method from ckanext-doi.

        :param metadata_dict: the metadata dict generated from build_metadata_dict
        :param xml_dict: XML dict to pass to datacite_compat.validator.validate()
        :returns: xml_dict
        """
        return xml_dict
