services:
  latest:
    build:
      context: .
      dockerfile: docker/Dockerfile_latest
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    depends_on:
      - db
      - solr
      - redis
    volumes:
      - ./ckanext:/base/src/ckanext-doi/ckanext
      - ./tests:/base/src/ckanext-doi/tests

  next:
    build:
      context: .
      dockerfile: docker/Dockerfile_next
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    depends_on:
      - db
      - solr
      - redis
    volumes:
      - ./ckanext:/base/src/ckanext-doi/ckanext
      - ./tests:/base/src/ckanext-doi/tests

  solr:
    image: ckan/ckan-solr:2.9
    logging:
      driver: none

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=ckan
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ckan
    logging:
      driver: none
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    tmpfs:
      - /var/lib/postgresql/data
    command: >
      postgres -c 'shared_buffers=128MB' -c 'max_connections=200'

  redis:
    image: redis:latest
    logging:
      driver: none
